---
title: "HB_Analysis"
author: "OVD"
date: "2023-05-24"
output: pdf_document
---

```{r}
library(readr)
library(tidyverse)

#setwd("/Users/ovd/Documents/GitHub/esg_pensions")

data2 = read_csv("conjoint2.csv")

data2 = as.data.frame(data2)

names(data2)
```

```{r}
cbc.tab = data2 %>% 
  select(pension,gender_equality, salary_equality, environmental_impact, firearms, living_wage, labor_rights, faith_morality) %>% 
  mutate(pension = -1 * pension)

table(cbc.tab$pension)

table(cbc.tab$gender_equality)

table(cbc.tab$salary_equality)

table(cbc.tab$environmental_impact)

table(cbc.tab$firearms)

table(cbc.tab$living_wage)

table(cbc.tab$labor_rights)

table(cbc.tab$faith_morality)
```

```{r}

#'*Following choicetools vignette*

cbc.tab = cbc.tab %>% 
  mutate(pension = case_when(pension == 40000 ~ 1,
                             pension == 45000 ~2,
                             pension == 50000 ~3,
                             pension == 55000 ~4,
                             pension == 60000 ~5,
                             pension ==65000 ~6,
                             pension ==70000 ~7),
         gender_mgmt = case_when(gender_equality == "no gender restrictions" ~ 1,
                              gender_equality == "gender restrictions" ~ 2),
         salary_equality = case_when(salary_equality == "no salary equality restrictions" ~ 1,
                                  salary_equality == "salary equality restrictions" ~ 2),
         environmental_impact = case_when(environmental_impact == "no environmental restrictions" ~1,
                                         environmental_impact == "environmental restrictions" ~2),
         firearms = case_when(firearms == "no firearms restrictions" ~1,
                                      firearms == "firearms restrictions" ~2),
         living_wage = case_when(living_wage == "no living wage restrictions" ~1,
                                      living_wage=="living wage restrictions"~2),
         labor_rights = case_when(labor_rights == "no labor rights restrictions" ~ 1,
                                  labor_rights == "labor rights restrictions" ~ 2),
         faith_morality = case_when(faith_morality == "no faith/morality restrictions" ~ 1,
                                    faith_morality == "faith/morality restrictions" ~2)) %>% 
  select(-gender_equality)

cbc.win = data2$choice_indicator

cbc.tasks = 12

cbc.concepts = 2

N = nrow(data2)/24
```

```{r}

cbc.attrs <- c(pension=7, gender_mgmt=2, salary_equality=2, environmental_impact=2, firearms=2, living_wage=2, labor_rights =2, faith_morality=2)

attr.list=cbc.attrs

cbc.levels    <- c("$40000", "$45000", "$50000", "$55000", "$60000", "$65000", "$70000",    # pension
                   "no gender restrictions", "gender restrictions",  # gender mgmt
                   "no salary equality restrictions",  "salary equality restrictions",  # salary equality
                   "no environmental restrictions",  "environmental restrictions",                          # environmental restrictions
                   "no firearms restrictions", "firearms restrictions", # firearms restrictions
                   "no living wage restrictions", "living wage restrictions",           # living wage
                   "no labor rights restrictions", "labor rights restrictions", # labor rights
                   "no faith/morality restrictions", "faith/morality restrictions") # faith morality

```


```{r}
library(choicetools)

cbc.hb <- estimateMNLfromDesignHB(tmp.des=cbc.tab, tmp.win=cbc.win, 
                                  kCards=cbc.concepts, kTrials=cbc.tasks,
                                  kResp=N , mcmcIters=50000)
```

```{r}
cbc.est        <- data.frame(extractHBbetas(cbc.hb, cbc.attrs))
names(cbc.est) <- cbc.levels
cbc.est$ID     <- 1:nrow(cbc.est)

library(ggplot2)
library(reshape2)
cbc.m <- melt(cbc.est, id.vars = "ID")

library(ggridges)
ggplot(data=cbc.m, aes(x=value, y=variable, group=variable)) +
      geom_density_ridges(scale=0.9, alpha=0, jittered_points=TRUE,
                          rel_min_height=0.005,
                          position="points_sina",
                          point_color = "blue", point_alpha=1/sqrt(N),
                          point_size=2.5) +
        ylab("Item") + 
        xlab("Relative preference (blue circles=individuals)") +
        ggtitle("Preference estimates: Distribution of individuals")
```

```{r}
#write_csv(cbc.est2, "cbc.est2.csv")

hbcj2 = as.data.frame(cbc.est)

```

```{r}
#Now calculate utility for money

RBetas <- read_csv("RBetas.csv")

diffs <- RBetas %>%
  mutate(
    # Calculate differences between successive coefficients
    diff1 = A1B2 - A1B1,
    diff2 = A1B3 - A1B2,
    # Continue calculating differences for all coefficient pairs
    diff3 = A1B4 - A1B3,
    diff4 = A1B5 - A1B4,
    diff5 = A1B6 - A1B5,
    diff6 = A1B7 - A1B6,

    # Compute the average difference
    avg_diff = (diff1 + diff2 + diff3 + diff4 + diff5 + diff6) / 6
  )

# Create a new data frame with just the average difference
df_avg_diff <- diffs %>%
  select(avg_diff)

# View the resulting data frame
View(df_avg_diff)

# Calculate the average difference per $1 change


df_avg_diff = df_avg_diff %>% 
  mutate(average_change_per_dollar = avg_diff/5000)
```


```{r}
# n should be 1082, not 1322!

RBetas$gender_mgmt = (RBetas$A2B1 - RBetas$A2B2)
RBetas$salary_equality = (RBetas$A3B1 - RBetas$A3B2)
RBetas$environmental_impact = (RBetas$A4B1 - RBetas$A4B2)
RBetas$firearms = (RBetas$A5B1 - RBetas$A5B2)
RBetas$living_wage = (RBetas$A6B1 - RBetas$A6B2)
RBetas$labor_rights = (RBetas$A7B1 - RBetas$A7B2)
RBetas$faith_morality = (RBetas$A8B1 - RBetas$A8B2)
```

```{r}

```


```{r}
RBetas$ut_per_dollar = df_avg_diff$average_change_per_dollar

RBetas$wtp_gender_mgmt = RBetas$gender_mgmt/RBetas$ut_per_dollar

RBetas$wtp_salary_equality = RBetas$salary_equality/RBetas$ut_per_dollar

RBetas$wtp_env_impact = RBetas$environmental_impact/RBetas$ut_per_dollar

RBetas$wtp_firearms = RBetas$firearms/RBetas$ut_per_dollar

RBetas$wtp_living_wage = RBetas$living_wage/RBetas$ut_per_dollar

RBetas$wtp_labor_rights = RBetas$labor_rights/RBetas$ut_per_dollar

RBetas$wtp_faith_morality = RBetas$faith_morality/RBetas$ut_per_dollar
```


```{r}
median(RBetas$wtp_living_wage)
```

```{r}
dfwtp2 = RBetas %>% 
  select(starts_with("wtp"))
```

```{r}
dfwtp2 = -1 * dfwtp2
```


```{r}
dfwtp.filt = RBetas %>% 
  filter(ut_per_dollar > 0) %>% 
  select(starts_with("wtp"))
```

```{r}
calculate_ci <- function(data, n_resample = 10000) {
  ci_results <- list()

  for (col in names(data)) {
    # Initialize vector for resampled statistics
    statistics_resampled <- numeric(n_resample)

    # Resampling loop
    for (i in 1:n_resample) {
      # Resample the data and calculate the median
      resampled_data <- sample(data[[col]], size = nrow(data), replace = TRUE)
      statistics_resampled[i] <- median(resampled_data)
    }

    # Calculate the median of the original data
    original_median <- median(data[[col]])

    # Calculate the 95% confidence interval
    ci_lower <- quantile(statistics_resampled, probs = 0.025)
    ci_upper <- quantile(statistics_resampled, probs = 0.975)

    # Store the results (including the original median)
    ci_results[[col]] <- c(Median = original_median, CI_Lower = ci_lower, CI_Upper = ci_upper)
  }

  return(ci_results)
}

```

```{r}
```

```{r}
calculate_ci(dfwtp.filt) #not even close to conjointly! Just use Conjointly to get that done and move on!

```





```{r}

# cbc.levels    <- c("$20,000" (1), "$25,000" (2), "$30,000" (3), "$35,000" (4), "$40,000" (5), "$45,000" (6), "$50,000" (7), "$55,000" (8), "$60,000" (9),    # pension (x9)
#                    "Invests in firearms", (10) 
#"Does not invests in firearms" (11),  # firearms
#                    "Invests in fossil fuels" (12),  "Does not invest in fossil fuels",  # fossil fuels (13)
#                    "Invests in firms that may employ children" (14),  "Invests in firms that ensure no children are employed" (15),                          # child labor
#                    "Does not advocate for racial diversity in management" (16), "Advocates for racial diversity in management" (17), # racial diversity
#                    "Does not advocate for equal pay for men and women" (18), "Advocates for equal pay for men and women" (19))           # equal pay 


cbc.levels    <- c("$40,000", "$45,000", "$50,000", "$55,000", "$60,000", "$65,000", "$70,000",    # pension
                   "no gender restrictions", "gender restrictions",  # gender mgmt
                   "no salary equality restrictions",  "salary equality restrictions",  # salary equality
                   "no environmental restrictions",  "environmental restrictions",                          # environmental restrictions
                   "no firearms restrictions", "firearms restrictions", # firearms restrictions
                   "no living wage restrictions", "living wage restrictions",           # living wage
                   "no labor rights restrictions", "labor rights restrictions", # labor rights
                   "no faith/morality restrictions", "faith/morality restrictions") # faith morality

prod1 <- c(1, 10, 12,  14, 16, 18)     # $40,000 pension with no sustainable features
prod2 <- c(1, 11, 13, 15, 17, 19)     # $40,000 pension with only sustainable features
usb.pref  <- marketSim(
  cbc.est,                    # matrix of individual-level utilities
  list(prod1, prod2),         # list of products to compare
  use.none=FALSE,             # we have no "none" column
  style="first")              # estimate share by first-choice approach

# see the overall preference share for the two products
colMeans(usb.pref)


```

```{r}
prod1 <- c(5, 10, 12,  14, 16, 18) 
prod2 <- c(5, 10, 13,  14, 16, 18) # environmental restriction

usb.pref  <- marketSim(
  cbc.est,                    # matrix of individual-level utilities
  list(prod1, prod2),         # list of products to compare
  use.none=FALSE,             # we have no "none" column
  style="first")              # estimate share by first-choice approach

# see the overall preference share for the two products
colMeans(usb.pref)

```


Multinomial Logit Model. Replicate with ChoiceModelR too! Follow vignettes.

 TBD

```{r}
#Compare no-ESG $45,000 vs ESG $40,000

prod3 <- c(1, 10, 12,  14, 16, 18)     # $40,000 pension with no sustainable features
#Defined above    # $40,000 pension with only sustainable features
usb.pref2  <- marketSim(
  cbc.est,                    # matrix of individual-level utilities
  list(prod3, prod2),         # list of products to compare
  use.none=FALSE,             # we have no "none" column
  style="first")              # estimate share by first-choice approach

# see the overall preference share for the two products
colMeans(usb.pref2)
```



