---
title: "Pensions ESG Pilot"
author: "OVD"
date: "2023-03-16"
output:
  bookdown::pdf_book:
    dev: cairo_pdf
---

```{r}
#setwd(dir = "/Users/ovd/Documents/GitHub/esg_pensions")

options(scipen=999)
```

```{r}
library(readr)

dfcj <- read_csv("rds_prod.experiment.392385.stacked.csv")
```


```{r message=FALSE, warning=FALSE}
library(cregg)
library(janitor)
library(tidyverse)
```

Import data and filter responses 0.5 or 1.5 * median completion time

```{r}

dfcj = dfcj %>% 
  clean_names() 

dfcj %>% 
  filter(q3_screen_out == "NULL" & 
           q6_screen_out == "NULL" & q8_screen_out == "NULL") 
# filter screen-outs (zero)
```

```{r}

median_complet_t = median(dfcj$respondent_length_of_interview_seconds) 
# calculate median completion time in secs

 dfcj = dfcj %>% 
  filter(respondent_length_of_interview_seconds >= 0.5 * median_complet_t,
         respondent_length_of_interview_seconds <= 1.5 * median_complet_t) 
 # filter responded too quickly or slowly
```


```{r}
#Transform variables to factors
dfcj = dfcj %>% 
  mutate(expected_pension_num = factor(expected_pension),
         firearms = factor(invests_in_firearms),                              
         fossil_fuels =  factor(invests_in_fossil_fuels),
         may_employ_children = factor(invests_in_firms_that_may_employ_children), 
         racial_diversity = factor(advocates_for_racial_diversity_in_management),
         gender_equal_pay = factor(advocates_for_equal_pay_for_men_and_women),
        choice_indicator = as.numeric(choice_indicator),
        prior = factor(ifelse(q9_would_you_prefer_to_restrict_your_investments_to_funds_that_take_environmental_social_and_governance_o2_no ==1, "anti-esg", "pro=esg")),
        republican = factor(ifelse(q12_if_you_don_t_identify_with_any_party_do_you_lean_towards_one_of_them_o1_republican ==1, 1,0)))

```

Vector for AMCE model and plot:
```{r}
f1 <- choice_indicator ~ expected_pension_num + firearms + fossil_fuels + 
  may_employ_children + racial_diversity + gender_equal_pay + prior + republican
#with factors re leveled

amce1 = amce(dfcj, f1, id = ~ survey_id)

plot(amce1)
```

WTP analysis. The logitr package uses a Hierarchical Bayesian model to estimate WTP and utilities from each attribute.

```{r}
library(logitr)
```

```{r}

dfcjtest = dfcj %>% 
  mutate(pension = expected_pension)


dfcjtest$pension <- recode(dfcjtest$pension,
                           "Expected pension: $20,000 a year" = "20,000", 
                           "Expected pension: $25,000 a year" = "25,000", 
                           "Expected pension: $30,000 a year" = "30,000", 
                           "Expected pension: $35,000 a year" = "35,000", 
                           "Expected pension: $40,000 a year" = "40,000", 
                           "Expected pension: $45,000 a year" = "45,000", 
                           "Expected pension: $50,000 a year" = "50,000")
```



```{r}
#transform to numeric

dfcjtest = dfcjtest %>%
   mutate(pension_num = readr::parse_number(pension)) 

```


```{r}
#import data for WTP analysis
library(readxl)
nochoice <- read_excel("~/Documents/GitHub/esg_pensions/nochoice.xlsx")
```

```{r}
ncl = pivot_longer(nochoice, cols = q1:q12, names_to = "choice")

ncl = ncl %>% 
  mutate(nc = ifelse(value == 3, 1, 0),
         choice_set = parse_number(choice),
         survey_id = ID) %>% 
  select(nc, choice_set, survey_id)
```

```{r}
#ok, now I need to create new var with the option not chosen
```


```{r}
dfnc = merge(dfcj, ncl, by = "survey_id", "choice_set")
```


```{r}

dfcjtest = dfcjtest %>% 
  arrange(survey_id, desc(choice_set)) %>% 
  mutate(obsID = as.integer(gl(2508, 2, labels = c(1: 2508))))


dfcjtest = dfcjtest %>% 
  select(survey_id, 
         obsID, 
         choice_set, 
         pension_num,
         choice_indicator, 
         firearms,
         fossil_fuels,
         may_employ_children,
         racial_diversity,
         gender_equal_pay)

dfcjtest2 = dfcjtest %>% 
  group_by(obsID) %>% # Create ID by group
  dplyr::mutate(ID = cur_group_id())
```

I will filter the data in republican/democrats to calculate the differences in WTP per group
```{r}

#removing none
dfcjtest3 = dfcjtest2 %>% 
  group_by(ID) %>% 
  filter(sum(choice_indicator) == 1)

#changing price to negative

dfcjtest3 = dfcjtest3 %>% 
  mutate(price = -1 * pension_num,
         firearms.num = ifelse(firearms == "Invests in firearms", 1, 0),
         fossil_fuels.num = ifelse(fossil_fuels == "Invests in fossil fuels", 1, 0),
         may_employ_children.num = ifelse(may_employ_children == "Invests in firms that may employ children", 1, 0),
         racial_diversity.num = ifelse(racial_diversity == "Does not advocate for racial diversity in management", 1, 0),
         gender_equal_pay.num = ifelse(gender_equal_pay == "Does not advocate for equal pay for men and women", 1, 0))



mnl_pref <- logitr(
    data    = dfcjtest3,
    outcome = "choice_indicator",
    obsID   = "ID",
    pars    = c("pension_num",
                "firearms.num", 
                "fossil_fuels.num",
                "may_employ_children.num",
                "racial_diversity.num",
                "gender_equal_pay.num")
)



mnl_wtp <- logitr(
    data     = dfcjtest3,
    outcome  = "choice_indicator",
    obsID    = "ID",
    pars     = c("firearms.num", 
                "fossil_fuels.num",
                "may_employ_children.num",
                "racial_diversity.num",
                "gender_equal_pay.num"),
    scalePar = "pension_num"
)

summary(mnl_pref)

summary(mnl_wtp)


```




